name: Master Deploy

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-22.04
    name: Deploying to Master Server
    steps:
      - name: Start Deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          password: ${{secrets.PASSWORD}}
          script: |
            cd /home/ubuntu/neo-ecom/neo-store
            git pull origin master
            npm install --force
            npm run build
            pm2 restart neo-store
            exit
